version: '3'

services:
  dns-server:
    image: ubuntu/bind9:latest
    container_name: dns-server
    ports:
      - '53:53/udp'
      - '53:53/tcp'
    volumes:
      - ./dns:/etc/bind
    restart: unless-stopped
    networks:
      - local-network

  pihole:
    image: pihole/pihole:latest
    platform: linux/arm64
    container_name: pihole
    environment:
      - TZ=Asia/Tokyo
      - WEBPASSWORD=adminpassword
    ports:
      - '8080:80'
      - '1053:53/udp'
      - '1053:53/tcp'
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
    networks:
      - local-network

  load-balancer:
    image: nginx:latest
    container_name: nginx-lb
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
      - '443:443'
    restart: unless-stopped
    networks:
      - local-network

  web1:
    image: node:18
    container_name: web1
    working_dir: /app
    volumes:
      - ./web:/app
    command: 'node server.js'
    environment:
      - SERVER_PORT=3000
      - SERVER_NAME=Web1
    ports:
      - '3000:3000'
    networks:
      - local-network

  web2:
    image: node:18
    container_name: web2
    working_dir: /app
    volumes:
      - ./web:/app
    command: 'node server.js'
    environment:
      - SERVER_PORT=3001
      - SERVER_NAME=Web2
    ports:
      - '3001:3001'
    networks:
      - local-network

networks:
  local-network:
